apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildkitd-cache
  namespace: woodpecker
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
