apiVersion: v1
kind: Service
metadata:
  name: buildkitd
  namespace: woodpecker
  labels:
    app: buildkitd
spec:
  selector:
    app: buildkitd
  ports:
    - name: buildkitd
      port: 1234
      targetPort: 1234
      protocol: TCP
  type: ClusterIP
