"""add product images table

Revision ID: 377444db97ce
Revises: 86af18fc13c2
Create Date: 2025-12-15 17:11:00.525186

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "377444db97ce"
down_revision: Union[str, Sequence[str], None] = "86af18fc13c2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_images",
        sa.Column(
            "tenant_id", sa.Uuid(), nullable=False, comment="Tenant ID for multi-tenant isolation"
        ),
        sa.Column("product_id", sa.Uuid(), nullable=False, comment="Product this image belongs to"),
        sa.Column(
            "image_url",
            sa.String(length=500),
            nullable=False,
            comment="Storage path/URL to the image file",
        ),
        sa.Column(
            "thumbnail_url",
            sa.String(length=500),
            nullable=True,
            comment="Storage path/URL to the thumbnail version",
        ),
        sa.Column(
            "alt_text",
            sa.String(length=255),
            server_default="",
            nullable=False,
            comment="Alt text for accessibility",
        ),
        sa.Column(
            "display_order",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Sort order for display (lower = first)",
        ),
        sa.Column(
            "is_primary",
            sa.Boolean(),
            server_default="false",
            nullable=False,
            comment="Whether this is the primary product image",
        ),
        sa.Column(
            "original_filename",
            sa.String(length=255),
            nullable=True,
            comment="Original uploaded filename",
        ),
        sa.Column("file_size", sa.Integer(), nullable=True, comment="File size in bytes"),
        sa.Column(
            "content_type", sa.String(length=100), nullable=True, comment="MIME type of the image"
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("product_id", "display_order", name="uq_product_image_order"),
        comment="Product images for shop display",
    )
    op.create_index(
        op.f("ix_product_images_product_id"), "product_images", ["product_id"], unique=False
    )
    op.create_index(
        op.f("ix_product_images_tenant_id"), "product_images", ["tenant_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_images_tenant_id"), table_name="product_images")
    op.drop_index(op.f("ix_product_images_product_id"), table_name="product_images")
    op.drop_table("product_images")
    # ### end Alembic commands ###
