"""add_designers_table

Revision ID: 79f717599971
Revises: f7b54ecedb28
Create Date: 2025-12-16 15:04:21.474106

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "79f717599971"
down_revision: Union[str, Sequence[str], None] = "f7b54ecedb28"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "designers",
        sa.Column(
            "tenant_id", sa.Uuid(), nullable=False, comment="Tenant ID for multi-tenant isolation"
        ),
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Designer display name (e.g., PrintyJay, CinderWings)",
        ),
        sa.Column(
            "slug",
            sa.String(length=100),
            nullable=False,
            comment="URL-friendly identifier (unique per tenant)",
        ),
        sa.Column(
            "logo_url", sa.String(length=500), nullable=True, comment="URL to designer logo image"
        ),
        sa.Column(
            "website_url",
            sa.String(length=500),
            nullable=True,
            comment="Designer website or store URL",
        ),
        sa.Column(
            "social_links",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Social media links as JSON (e.g., {instagram: url, youtube: url})",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Designer bio/description for profile page",
        ),
        sa.Column(
            "membership_cost",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Annual/monthly membership cost",
        ),
        sa.Column(
            "membership_start_date", sa.Date(), nullable=True, comment="When membership started"
        ),
        sa.Column(
            "membership_renewal_date",
            sa.Date(),
            nullable=True,
            comment="Next renewal date for membership",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Whether designer is currently active/licensed",
        ),
        sa.Column(
            "notes",
            sa.Text(),
            nullable=True,
            comment="Internal notes about the designer/membership",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_designer_tenant_slug"),
    )
    op.create_index(op.f("ix_designers_slug"), "designers", ["slug"], unique=False)
    op.create_index(op.f("ix_designers_tenant_id"), "designers", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_designers_tenant_id"), table_name="designers")
    op.drop_index(op.f("ix_designers_slug"), table_name="designers")
    op.drop_table("designers")
    # ### end Alembic commands ###
