"""add_multi_plate_support_printers_configs_plates

Revision ID: 86af18fc13c2
Revises: ede22cd894be
Create Date: 2025-12-15 14:37:44.304047

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "86af18fc13c2"
down_revision: Union[str, Sequence[str], None] = "ede22cd894be"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def column_exists(table_name: str, column_name: str) -> bool:
    """Check if a column exists in a table."""
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            """
            SELECT EXISTS (
                SELECT 1 FROM information_schema.columns
                WHERE table_name = :table_name AND column_name = :column_name
            )
            """
        ),
        {"table_name": table_name, "column_name": column_name},
    )
    return result.scalar()


def index_exists(index_name: str) -> bool:
    """Check if an index exists."""
    conn = op.get_bind()
    result = conn.execute(
        sa.text(
            """
            SELECT EXISTS (
                SELECT 1 FROM pg_indexes
                WHERE indexname = :index_name
            )
            """
        ),
        {"index_name": index_name},
    )
    return result.scalar()


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "model_printer_configs",
        "model_id",
        existing_type=sa.UUID(),
        comment="Model this config applies to",
        existing_nullable=False,
    )
    op.alter_column(
        "model_printer_configs",
        "printer_id",
        existing_type=sa.UUID(),
        comment="Printer this config is for",
        existing_nullable=False,
    )
    op.alter_column(
        "model_printer_configs",
        "slicer_settings",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="Additional slicer settings (speed, retraction, etc.)",
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("idx_model_printer_configs_model"), table_name="model_printer_configs")
    op.drop_index(op.f("idx_model_printer_configs_printer"), table_name="model_printer_configs")
    op.create_index(
        op.f("ix_model_printer_configs_model_id"),
        "model_printer_configs",
        ["model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_model_printer_configs_printer_id"),
        "model_printer_configs",
        ["printer_id"],
        unique=False,
    )
    # Only add prints_per_plate if it doesn't already exist (may have been added by earlier migration)
    if not column_exists("models", "prints_per_plate"):
        op.add_column(
            "models",
            sa.Column(
                "prints_per_plate",
                sa.Integer(),
                server_default="1",
                nullable=False,
                comment="Number of items printed per plate (for batch printing). Material weights and print time are divided by this.",
            ),
        )
    op.alter_column(
        "models",
        "print_time_minutes",
        existing_type=sa.INTEGER(),
        comment="Print time in minutes (for full plate if prints_per_plate > 1)",
        existing_comment="Estimated print time in minutes",
        existing_nullable=True,
    )
    op.alter_column(
        "printers",
        "tenant_id",
        existing_type=sa.UUID(),
        comment="Tenant ID for multi-tenant isolation",
        existing_nullable=False,
    )
    op.alter_column(
        "printers",
        "name",
        existing_type=sa.VARCHAR(length=100),
        comment="Printer name (e.g., 'Bambu A1 Mini')",
        existing_comment='Printer name (e.g., "Bambu A1 Mini")',
        existing_nullable=False,
    )
    op.alter_column(
        "printers",
        "capabilities",
        existing_type=postgresql.JSONB(astext_type=sa.Text()),
        type_=sa.JSON(),
        existing_comment="Printer capabilities (AMS, materials, etc.)",
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.drop_index(op.f("idx_printers_active"), table_name="printers")
    op.drop_index(op.f("idx_printers_tenant"), table_name="printers")
    op.create_index(op.f("ix_printers_tenant_id"), "printers", ["tenant_id"], unique=False)
    # Make production_run_materials column additions idempotent
    if not column_exists("production_run_materials", "estimated_model_weight_grams"):
        op.add_column(
            "production_run_materials",
            sa.Column(
                "estimated_model_weight_grams", sa.Numeric(precision=10, scale=2), nullable=False
            ),
        )
    if not column_exists("production_run_materials", "estimated_flushed_grams"):
        op.add_column(
            "production_run_materials",
            sa.Column("estimated_flushed_grams", sa.Numeric(precision=10, scale=2), nullable=False),
        )
    if not column_exists("production_run_materials", "estimated_tower_grams"):
        op.add_column(
            "production_run_materials",
            sa.Column("estimated_tower_grams", sa.Numeric(precision=10, scale=2), nullable=False),
        )
    if not column_exists("production_run_materials", "actual_model_weight_grams"):
        op.add_column(
            "production_run_materials",
            sa.Column(
                "actual_model_weight_grams", sa.Numeric(precision=10, scale=2), nullable=True
            ),
        )
    if not column_exists("production_run_materials", "actual_flushed_grams"):
        op.add_column(
            "production_run_materials",
            sa.Column("actual_flushed_grams", sa.Numeric(precision=10, scale=2), nullable=True),
        )
    if not column_exists("production_run_materials", "actual_tower_grams"):
        op.add_column(
            "production_run_materials",
            sa.Column("actual_tower_grams", sa.Numeric(precision=10, scale=2), nullable=True),
        )
    # Make drop_column operations idempotent (only drop if exists)
    if column_exists("production_run_materials", "estimated_weight_grams"):
        op.drop_column("production_run_materials", "estimated_weight_grams")
    if column_exists("production_run_materials", "actual_weight_manual"):
        op.drop_column("production_run_materials", "actual_weight_manual")
    if column_exists("production_run_materials", "actual_purge_grams"):
        op.drop_column("production_run_materials", "actual_purge_grams")
    if column_exists("production_run_materials", "estimated_purge_grams"):
        op.drop_column("production_run_materials", "estimated_purge_grams")
    op.alter_column(
        "production_run_plates",
        "production_run_id",
        existing_type=sa.UUID(),
        comment="Production run this plate belongs to",
        existing_nullable=False,
    )
    op.alter_column(
        "production_run_plates",
        "plate_name",
        existing_type=sa.VARCHAR(length=200),
        comment="Plate name (e.g., 'Dragon Bodies (A1 Mini)')",
        existing_comment='Plate name (e.g., "Dragon Bodies (A1 Mini)")',
        existing_nullable=False,
    )
    op.drop_index(op.f("idx_production_run_plates_model"), table_name="production_run_plates")
    op.drop_index(
        op.f("idx_production_run_plates_plate_number"), table_name="production_run_plates"
    )
    op.drop_index(op.f("idx_production_run_plates_printer"), table_name="production_run_plates")
    op.drop_index(op.f("idx_production_run_plates_run"), table_name="production_run_plates")
    op.drop_index(op.f("idx_production_run_plates_status"), table_name="production_run_plates")
    op.create_index(
        op.f("ix_production_run_plates_model_id"),
        "production_run_plates",
        ["model_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_run_plates_printer_id"),
        "production_run_plates",
        ["printer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_run_plates_production_run_id"),
        "production_run_plates",
        ["production_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_run_plates_status"), "production_run_plates", ["status"], unique=False
    )
    # Make production_runs add_column operations idempotent
    if not column_exists("production_runs", "estimated_model_weight_grams"):
        op.add_column(
            "production_runs",
            sa.Column(
                "estimated_model_weight_grams", sa.Numeric(precision=10, scale=2), nullable=True
            ),
        )
    if not column_exists("production_runs", "estimated_flushed_grams"):
        op.add_column(
            "production_runs",
            sa.Column("estimated_flushed_grams", sa.Numeric(precision=10, scale=2), nullable=True),
        )
    if not column_exists("production_runs", "estimated_tower_grams"):
        op.add_column(
            "production_runs",
            sa.Column("estimated_tower_grams", sa.Numeric(precision=10, scale=2), nullable=True),
        )
    if not column_exists("production_runs", "estimated_total_weight_grams"):
        op.add_column(
            "production_runs",
            sa.Column(
                "estimated_total_weight_grams", sa.Numeric(precision=10, scale=2), nullable=True
            ),
        )
    if not column_exists("production_runs", "actual_model_weight_grams"):
        op.add_column(
            "production_runs",
            sa.Column(
                "actual_model_weight_grams", sa.Numeric(precision=10, scale=2), nullable=True
            ),
        )
    if not column_exists("production_runs", "actual_flushed_grams"):
        op.add_column(
            "production_runs",
            sa.Column("actual_flushed_grams", sa.Numeric(precision=10, scale=2), nullable=True),
        )
    if not column_exists("production_runs", "actual_tower_grams"):
        op.add_column(
            "production_runs",
            sa.Column("actual_tower_grams", sa.Numeric(precision=10, scale=2), nullable=True),
        )
    if not column_exists("production_runs", "actual_total_weight_grams"):
        op.add_column(
            "production_runs",
            sa.Column(
                "actual_total_weight_grams", sa.Numeric(precision=10, scale=2), nullable=True
            ),
        )
    # Make production_runs drop_column operations idempotent
    if column_exists("production_runs", "actual_total_purge_grams"):
        op.drop_column("production_runs", "actual_total_purge_grams")
    if column_exists("production_runs", "actual_total_filament_grams"):
        op.drop_column("production_runs", "actual_total_filament_grams")
    if column_exists("production_runs", "estimated_total_purge_grams"):
        op.drop_column("production_runs", "estimated_total_purge_grams")
    if column_exists("production_runs", "estimated_total_filament_grams"):
        op.drop_column("production_runs", "estimated_total_filament_grams")
    # Make products add_column operations idempotent
    if not column_exists("products", "packaging_consumable_id"):
        op.add_column(
            "products",
            sa.Column(
                "packaging_consumable_id",
                sa.Uuid(),
                nullable=True,
                comment="Optional consumable used for packaging (e.g., box)",
            ),
        )
    if not column_exists("products", "packaging_quantity"):
        op.add_column(
            "products",
            sa.Column(
                "packaging_quantity",
                sa.Integer(),
                server_default="1",
                nullable=False,
                comment="Quantity of packaging consumable per product",
            ),
        )
    op.alter_column(
        "products",
        "packaging_cost",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="Manual packaging cost per product (used if no consumable linked)",
        existing_comment="Cost of packaging per product",
        existing_nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    # Note: ix_products_packaging_consumable_id already created in n1o2p3q4r5s6
    op.create_foreign_key(
        None,
        "products",
        "consumable_types",
        ["packaging_consumable_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "products", type_="foreignkey")
    # Note: ix_products_packaging_consumable_id dropped in n1o2p3q4r5s6 downgrade
    op.alter_column(
        "products",
        "packaging_cost",
        existing_type=sa.NUMERIC(precision=10, scale=2),
        comment="Cost of packaging per product",
        existing_comment="Manual packaging cost per product (used if no consumable linked)",
        existing_nullable=False,
        existing_server_default=sa.text("'0'::numeric"),
    )
    op.drop_column("products", "packaging_quantity")
    op.drop_column("products", "packaging_consumable_id")
    op.add_column(
        "production_runs",
        sa.Column(
            "estimated_total_filament_grams",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "production_runs",
        sa.Column(
            "estimated_total_purge_grams",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "production_runs",
        sa.Column(
            "actual_total_filament_grams",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "production_runs",
        sa.Column(
            "actual_total_purge_grams",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("production_runs", "actual_total_weight_grams")
    op.drop_column("production_runs", "actual_tower_grams")
    op.drop_column("production_runs", "actual_flushed_grams")
    op.drop_column("production_runs", "actual_model_weight_grams")
    op.drop_column("production_runs", "estimated_total_weight_grams")
    op.drop_column("production_runs", "estimated_tower_grams")
    op.drop_column("production_runs", "estimated_flushed_grams")
    op.drop_column("production_runs", "estimated_model_weight_grams")
    op.drop_index(op.f("ix_production_run_plates_status"), table_name="production_run_plates")
    op.drop_index(
        op.f("ix_production_run_plates_production_run_id"), table_name="production_run_plates"
    )
    op.drop_index(op.f("ix_production_run_plates_printer_id"), table_name="production_run_plates")
    op.drop_index(op.f("ix_production_run_plates_model_id"), table_name="production_run_plates")
    op.create_index(
        op.f("idx_production_run_plates_status"), "production_run_plates", ["status"], unique=False
    )
    op.create_index(
        op.f("idx_production_run_plates_run"),
        "production_run_plates",
        ["production_run_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_production_run_plates_printer"),
        "production_run_plates",
        ["printer_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_production_run_plates_plate_number"),
        "production_run_plates",
        ["production_run_id", "plate_number"],
        unique=False,
    )
    op.create_index(
        op.f("idx_production_run_plates_model"), "production_run_plates", ["model_id"], unique=False
    )
    op.alter_column(
        "production_run_plates",
        "plate_name",
        existing_type=sa.VARCHAR(length=200),
        comment='Plate name (e.g., "Dragon Bodies (A1 Mini)")',
        existing_comment="Plate name (e.g., 'Dragon Bodies (A1 Mini)')",
        existing_nullable=False,
    )
    op.alter_column(
        "production_run_plates",
        "production_run_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Production run this plate belongs to",
        existing_nullable=False,
    )
    op.add_column(
        "production_run_materials",
        sa.Column(
            "estimated_purge_grams",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "production_run_materials",
        sa.Column(
            "actual_purge_grams",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "production_run_materials",
        sa.Column(
            "actual_weight_manual",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "production_run_materials",
        sa.Column(
            "estimated_weight_grams",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_column("production_run_materials", "actual_tower_grams")
    op.drop_column("production_run_materials", "actual_flushed_grams")
    op.drop_column("production_run_materials", "actual_model_weight_grams")
    op.drop_column("production_run_materials", "estimated_tower_grams")
    op.drop_column("production_run_materials", "estimated_flushed_grams")
    op.drop_column("production_run_materials", "estimated_model_weight_grams")
    op.drop_index(op.f("ix_printers_tenant_id"), table_name="printers")
    op.create_index(op.f("idx_printers_tenant"), "printers", ["tenant_id"], unique=False)
    op.create_index(op.f("idx_printers_active"), "printers", ["is_active"], unique=False)
    op.alter_column(
        "printers",
        "capabilities",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="Printer capabilities (AMS, materials, etc.)",
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "printers",
        "name",
        existing_type=sa.VARCHAR(length=100),
        comment='Printer name (e.g., "Bambu A1 Mini")',
        existing_comment="Printer name (e.g., 'Bambu A1 Mini')",
        existing_nullable=False,
    )
    op.alter_column(
        "printers",
        "tenant_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Tenant ID for multi-tenant isolation",
        existing_nullable=False,
    )
    op.alter_column(
        "models",
        "print_time_minutes",
        existing_type=sa.INTEGER(),
        comment="Estimated print time in minutes",
        existing_comment="Print time in minutes (for full plate if prints_per_plate > 1)",
        existing_nullable=True,
    )
    op.drop_column("models", "prints_per_plate")
    op.drop_index(op.f("ix_model_printer_configs_printer_id"), table_name="model_printer_configs")
    op.drop_index(op.f("ix_model_printer_configs_model_id"), table_name="model_printer_configs")
    op.create_index(
        op.f("idx_model_printer_configs_printer"),
        "model_printer_configs",
        ["printer_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_model_printer_configs_model"), "model_printer_configs", ["model_id"], unique=False
    )
    op.alter_column(
        "model_printer_configs",
        "slicer_settings",
        existing_type=sa.JSON(),
        type_=postgresql.JSONB(astext_type=sa.Text()),
        existing_comment="Additional slicer settings (speed, retraction, etc.)",
        existing_nullable=True,
        existing_server_default=sa.text("'{}'::jsonb"),
    )
    op.alter_column(
        "model_printer_configs",
        "printer_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Printer this config is for",
        existing_nullable=False,
    )
    op.alter_column(
        "model_printer_configs",
        "model_id",
        existing_type=sa.UUID(),
        comment=None,
        existing_comment="Model this config applies to",
        existing_nullable=False,
    )
    # ### end Alembic commands ###
