"""Initial schema - tenants, users, material_types

Revision ID: 9521683a2066
Revises:
Create Date: 2025-10-30 20:43:29.637109

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9521683a2066"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "material_types",
        sa.Column(
            "name",
            sa.String(length=100),
            nullable=False,
            comment="Material name (e.g., PLA, PETG, ASA)",
        ),
        sa.Column(
            "code",
            sa.String(length=20),
            nullable=False,
            comment="Short code for material (e.g., PLA, PETG)",
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
            comment="Description of material properties and uses",
        ),
        sa.Column(
            "typical_density",
            sa.Float(),
            nullable=True,
            comment="Typical density in g/cm³ (e.g., 1.24 for PLA)",
        ),
        sa.Column(
            "typical_cost_per_kg",
            sa.Float(),
            nullable=True,
            comment="Typical cost per kilogram (for defaults)",
        ),
        sa.Column(
            "min_temp", sa.Integer(), nullable=True, comment="Minimum printing temperature (°C)"
        ),
        sa.Column(
            "max_temp", sa.Integer(), nullable=True, comment="Maximum printing temperature (°C)"
        ),
        sa.Column("bed_temp", sa.Integer(), nullable=True, comment="Typical bed temperature (°C)"),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether this material type is active",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_material_types_code"), "material_types", ["code"], unique=True)
    op.create_index(op.f("ix_material_types_name"), "material_types", ["name"], unique=True)
    op.create_table(
        "tenants",
        sa.Column(
            "name", sa.String(length=255), nullable=False, comment="Tenant/Organization name"
        ),
        sa.Column(
            "slug", sa.String(length=100), nullable=False, comment="URL-safe identifier for tenant"
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether tenant is active (for soft deletion)",
        ),
        sa.Column(
            "settings",
            sa.JSON(),
            nullable=False,
            comment="Tenant-specific settings (branding, preferences, etc.)",
        ),
        sa.Column(
            "description", sa.Text(), nullable=True, comment="Description of the tenant/business"
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_tenants_name"), "tenants", ["name"], unique=False)
    op.create_index(op.f("ix_tenants_slug"), "tenants", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column(
            "authentik_user_id",
            sa.String(length=255),
            nullable=False,
            comment="Authentik user ID (from OIDC 'sub' claim)",
        ),
        sa.Column("email", sa.String(length=255), nullable=False, comment="User email address"),
        sa.Column("full_name", sa.String(length=255), nullable=True, comment="User's full name"),
        sa.Column(
            "is_active", sa.Boolean(), nullable=False, comment="Whether user account is active"
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_authentik_user_id"), "users", ["authentik_user_id"], unique=True)
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "user_tenants",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("tenant_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role", sa.String(length=50), nullable=False, comment="User's role within this tenant"
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "tenant_id", name="uq_user_tenant"),
        comment="User-Tenant relationship with roles",
    )
    op.create_index(op.f("ix_user_tenants_tenant_id"), "user_tenants", ["tenant_id"], unique=False)
    op.create_index(op.f("ix_user_tenants_user_id"), "user_tenants", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_tenants_user_id"), table_name="user_tenants")
    op.drop_index(op.f("ix_user_tenants_tenant_id"), table_name="user_tenants")
    op.drop_table("user_tenants")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_authentik_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_tenants_slug"), table_name="tenants")
    op.drop_index(op.f("ix_tenants_name"), table_name="tenants")
    op.drop_table("tenants")
    op.drop_index(op.f("ix_material_types_name"), table_name="material_types")
    op.drop_index(op.f("ix_material_types_code"), table_name="material_types")
    op.drop_table("material_types")
    # ### end Alembic commands ###
