"""add_categories_table

Revision ID: aab1994dc0bc
Revises: 377444db97ce
Create Date: 2025-12-15 17:37:08.014790

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "aab1994dc0bc"
down_revision: Union[str, Sequence[str], None] = "377444db97ce"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column(
            "tenant_id", sa.Uuid(), nullable=False, comment="Tenant ID for multi-tenant isolation"
        ),
        sa.Column("name", sa.String(length=100), nullable=False, comment="Category display name"),
        sa.Column(
            "slug",
            sa.String(length=100),
            nullable=False,
            comment="URL-friendly identifier (unique per tenant)",
        ),
        sa.Column("description", sa.Text(), nullable=True, comment="Category description"),
        sa.Column(
            "display_order",
            sa.Integer(),
            server_default="0",
            nullable=False,
            comment="Sort order for display (lower = first)",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            server_default="true",
            nullable=False,
            comment="Whether category is visible in shop",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "slug", name="uq_category_tenant_slug"),
    )
    op.create_index(op.f("ix_categories_slug"), "categories", ["slug"], unique=False)
    op.create_index(op.f("ix_categories_tenant_id"), "categories", ["tenant_id"], unique=False)
    op.create_table(
        "product_categories",
        sa.Column("product_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["product_id"], ["products.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("product_id", "category_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_categories")
    op.drop_index(op.f("ix_categories_tenant_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_slug"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
