"""Add spools table for filament inventory

Revision ID: d80bf772b461
Revises: 9521683a2066
Create Date: 2025-10-30 21:44:12.416700

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d80bf772b461"
down_revision: Union[str, Sequence[str], None] = "9521683a2066"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "spools",
        sa.Column(
            "tenant_id", sa.Uuid(), nullable=False, comment="Tenant ID for multi-tenant isolation"
        ),
        sa.Column(
            "material_type_id", sa.Uuid(), nullable=False, comment="Material type (PLA, PETG, etc.)"
        ),
        sa.Column(
            "spool_id",
            sa.String(length=50),
            nullable=False,
            comment="User-friendly spool ID (e.g., FIL-001, PLA-RED-001)",
        ),
        sa.Column(
            "brand", sa.String(length=100), nullable=False, comment="Filament brand/manufacturer"
        ),
        sa.Column("color", sa.String(length=50), nullable=False, comment="Filament color"),
        sa.Column(
            "finish",
            sa.String(length=50),
            nullable=True,
            comment="Finish type (matte, glossy, metallic, etc.)",
        ),
        sa.Column(
            "initial_weight",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Initial spool weight in grams (e.g., 1000.00 for 1kg)",
        ),
        sa.Column(
            "current_weight",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
            comment="Current spool weight in grams",
        ),
        sa.Column(
            "purchase_date",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Date spool was purchased",
        ),
        sa.Column(
            "purchase_price",
            sa.Numeric(precision=10, scale=2),
            nullable=True,
            comment="Purchase price in local currency",
        ),
        sa.Column("supplier", sa.String(length=100), nullable=True, comment="Supplier/vendor name"),
        sa.Column(
            "storage_location",
            sa.String(length=100),
            nullable=True,
            comment="Physical storage location (e.g., Shelf A, Box 3)",
        ),
        sa.Column("notes", sa.Text(), nullable=True, comment="Additional notes about this spool"),
        sa.Column(
            "qr_code_id",
            sa.String(length=100),
            nullable=True,
            comment="QR code identifier for quick scanning",
        ),
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            comment="Whether spool is active (not empty/discarded)",
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["material_type_id"],
            ["material_types.id"],
        ),
        sa.ForeignKeyConstraint(["tenant_id"], ["tenants.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_spools_material_type_id"), "spools", ["material_type_id"], unique=False
    )
    op.create_index(op.f("ix_spools_qr_code_id"), "spools", ["qr_code_id"], unique=True)
    op.create_index(op.f("ix_spools_spool_id"), "spools", ["spool_id"], unique=False)
    op.create_index(op.f("ix_spools_tenant_id"), "spools", ["tenant_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_spools_tenant_id"), table_name="spools")
    op.drop_index(op.f("ix_spools_spool_id"), table_name="spools")
    op.drop_index(op.f("ix_spools_qr_code_id"), table_name="spools")
    op.drop_index(op.f("ix_spools_material_type_id"), table_name="spools")
    op.drop_table("spools")
    # ### end Alembic commands ###
