"""Add shop visibility and featured fields to products and categories

Revision ID: f7b54ecedb28
Revises: aab1994dc0bc
Create Date: 2025-12-15 21:06:44.834655

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f7b54ecedb28"
down_revision: Union[str, Sequence[str], None] = "aab1994dc0bc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "categories",
        sa.Column(
            "image_url",
            sa.String(length=500),
            nullable=True,
            comment="Hero/banner image URL for category page in shop",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "shop_visible",
            sa.Boolean(),
            nullable=False,
            server_default="false",
            comment="Whether product appears in the online shop",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "shop_description",
            sa.Text(),
            nullable=True,
            comment="Rich HTML description for shop display (falls back to description if null)",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "is_featured",
            sa.Boolean(),
            nullable=False,
            server_default="false",
            comment="Whether product is featured in showcase/gallery",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "feature_title",
            sa.String(length=100),
            nullable=True,
            comment="Custom title for featured display (e.g., dragon name)",
        ),
    )
    op.add_column(
        "products",
        sa.Column(
            "backstory",
            sa.Text(),
            nullable=True,
            comment="Backstory/lore for featured items (dragons, special editions)",
        ),
    )
    op.create_index(op.f("ix_products_is_featured"), "products", ["is_featured"], unique=False)
    op.create_index(op.f("ix_products_shop_visible"), "products", ["shop_visible"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_products_shop_visible"), table_name="products")
    op.drop_index(op.f("ix_products_is_featured"), table_name="products")
    op.drop_column("products", "backstory")
    op.drop_column("products", "feature_title")
    op.drop_column("products", "is_featured")
    op.drop_column("products", "shop_description")
    op.drop_column("products", "shop_visible")
    op.drop_column("categories", "image_url")
    # ### end Alembic commands ###
