"""Pydantic schemas for API requests and responses."""

from app.schemas.consumable import (
    ConsumablePurchaseCreate,
    ConsumablePurchaseListResponse,
    ConsumablePurchaseResponse,
    ConsumablePurchaseUpdate,
    ConsumablePurchaseWithType,
    ConsumableTypeCreate,
    ConsumableTypeListResponse,
    ConsumableTypeResponse,
    ConsumableTypeUpdate,
    ConsumableUsageCreate,
    ConsumableUsageListResponse,
    ConsumableUsageResponse,
    ConsumableUsageWithDetails,
    LowStockAlert,
    StockAdjustment,
)
from app.schemas.model import (
    CostBreakdown,
    ModelBase,
    ModelComponentBase,
    ModelComponentCreate,
    ModelComponentResponse,
    ModelCreate,
    ModelDetailResponse,
    ModelListResponse,
    ModelMaterialBase,
    ModelMaterialCreate,
    ModelMaterialResponse,
    ModelResponse,
    ModelUpdate,
)
from app.schemas.model_printer_config import (
    ModelPrinterConfigBase,
    ModelPrinterConfigCreate,
    ModelPrinterConfigListResponse,
    ModelPrinterConfigResponse,
    ModelPrinterConfigSummary,
    ModelPrinterConfigUpdate,
)
from app.schemas.printer import (
    PrinterBase,
    PrinterCreate,
    PrinterListResponse,
    PrinterResponse,
    PrinterSummary,
    PrinterUpdate,
)
from app.schemas.printer_connection import (
    BambuPrinterStatus,
    ConnectionType,
    PrinterConnectionCreate,
    PrinterConnectionResponse,
    PrinterConnectionStatus,
    PrinterConnectionUpdate,
)
from app.schemas.ams_slot_mapping import (
    AMSFullStatus,
    AMSSlotBulkMapRequest,
    AMSSlotListResponse,
    AMSSlotMappingCreate,
    AMSSlotMappingResponse,
    AMSSlotMappingUpdate,
    AMSSlotMappingWithSpool,
    AMSStatusFromMQTT,
    AMSTrayStatus,
    SpoolSummaryForAMS,
)
from app.schemas.product import (
    ProductBase,
    ProductCostBreakdown,
    ProductCreate,
    ProductDetailResponse,
    ProductListResponse,
    ProductModelBase,
    ProductModelCreate,
    ProductModelResponse,
    ProductPricingBase,
    ProductPricingCreate,
    ProductPricingResponse,
    ProductPricingUpdate,
    ProductResponse,
    ProductUpdate,
)
from app.schemas.production_run import (
    ProductionRunBase,
    ProductionRunCreate,
    ProductionRunCreateRequest,
    ProductionRunUpdate,
    ProductionRunResponse,
    ProductionRunDetailResponse,
    ProductionRunListResponse,
    ProductionRunItemBase,
    ProductionRunItemCreate,
    ProductionRunItemUpdate,
    ProductionRunItemResponse,
    ProductionRunMaterialBase,
    ProductionRunMaterialCreate,
    ProductionRunMaterialUpdate,
    ProductionRunMaterialResponse,
    ModelSummary,
    ProductSummary,
)
from app.schemas.production_run_plate import (
    ProductionRunPlateBase,
    ProductionRunPlateCreate,
    ProductionRunPlateListResponse,
    ProductionRunPlateResponse,
    ProductionRunPlateSummary,
    ProductionRunPlateUpdate,
    MarkPlateCompleteRequest,
)
from app.schemas.spool import SpoolCreate, SpoolResponse, SpoolUpdate
from app.schemas.spoolmandb import (
    SpoolmanDBFilamentListResponse,
    SpoolmanDBFilamentResponse,
    SpoolmanDBFilamentWithManufacturer,
    SpoolmanDBManufacturerListResponse,
    SpoolmanDBManufacturerResponse,
    SpoolmanDBManufacturerWithCount,
    SpoolmanDBStatsResponse,
    SpoolmanDBSyncResponse,
)
from app.schemas.payment import (
    CartItem,
    CustomerDetails,
    PaymentError,
    PaymentRequest,
    PaymentResponse,
    ShippingAddress,
)
from app.schemas.designer import (
    DesignerCreate,
    DesignerListResponse,
    DesignerPublic,
    DesignerResponse,
    DesignerSimple,
    DesignerUpdate,
)
from app.schemas.shop import (
    ShopCategoryListResponse,
    ShopCategoryResponse,
    ShopCategorySummary,
    ShopDragonListResponse,
    ShopProductDetail,
    ShopProductFilters,
    ShopProductImageResponse,
    ShopProductListResponse,
    ShopProductSummary,
)
from app.schemas.tenant_settings import (
    SquareConnectionTest,
    SquareSettingsResponse,
    SquareSettingsUpdate,
    TenantMemberInvite,
    TenantMemberListResponse,
    TenantMemberResponse,
    TenantMemberRoleUpdate,
    TenantResponse,
    TenantUpdate,
    UserRole,
)

__all__ = [
    # Spool schemas
    "SpoolCreate",
    "SpoolUpdate",
    "SpoolResponse",
    # Consumable Type schemas
    "ConsumableTypeCreate",
    "ConsumableTypeUpdate",
    "ConsumableTypeResponse",
    "ConsumableTypeListResponse",
    # Consumable Purchase schemas
    "ConsumablePurchaseCreate",
    "ConsumablePurchaseUpdate",
    "ConsumablePurchaseResponse",
    "ConsumablePurchaseWithType",
    "ConsumablePurchaseListResponse",
    # Consumable Usage schemas
    "ConsumableUsageCreate",
    "ConsumableUsageResponse",
    "ConsumableUsageWithDetails",
    "ConsumableUsageListResponse",
    # Consumable helpers
    "StockAdjustment",
    "LowStockAlert",
    # Model schemas (printed items)
    "ModelBase",
    "ModelCreate",
    "ModelUpdate",
    "ModelResponse",
    "ModelDetailResponse",
    "ModelListResponse",
    # Model Material (BOM) schemas
    "ModelMaterialBase",
    "ModelMaterialCreate",
    "ModelMaterialResponse",
    # Model Component schemas
    "ModelComponentBase",
    "ModelComponentCreate",
    "ModelComponentResponse",
    # Model Cost schemas
    "CostBreakdown",
    # Printer schemas (3D printers)
    "PrinterBase",
    "PrinterCreate",
    "PrinterUpdate",
    "PrinterResponse",
    "PrinterListResponse",
    "PrinterSummary",
    # Printer Connection schemas (Bambu, OctoPrint, etc.)
    "ConnectionType",
    "PrinterConnectionCreate",
    "PrinterConnectionUpdate",
    "PrinterConnectionResponse",
    "PrinterConnectionStatus",
    "BambuPrinterStatus",
    # AMS Slot Mapping schemas
    "AMSSlotMappingCreate",
    "AMSSlotMappingUpdate",
    "AMSSlotMappingResponse",
    "AMSSlotMappingWithSpool",
    "AMSSlotListResponse",
    "AMSSlotBulkMapRequest",
    "AMSStatusFromMQTT",
    "AMSTrayStatus",
    "AMSFullStatus",
    "SpoolSummaryForAMS",
    # ModelPrinterConfig schemas (printer-specific model settings)
    "ModelPrinterConfigBase",
    "ModelPrinterConfigCreate",
    "ModelPrinterConfigUpdate",
    "ModelPrinterConfigResponse",
    "ModelPrinterConfigListResponse",
    "ModelPrinterConfigSummary",
    # Product schemas (sellable items)
    "ProductBase",
    "ProductCreate",
    "ProductUpdate",
    "ProductResponse",
    "ProductDetailResponse",
    "ProductListResponse",
    # Product Model (composition) schemas
    "ProductModelBase",
    "ProductModelCreate",
    "ProductModelResponse",
    # Product Pricing schemas
    "ProductPricingBase",
    "ProductPricingCreate",
    "ProductPricingUpdate",
    "ProductPricingResponse",
    # Product Cost schemas
    "ProductCostBreakdown",
    # Production Run schemas
    "ProductionRunBase",
    "ProductionRunCreate",
    "ProductionRunCreateRequest",
    "ProductionRunUpdate",
    "ProductionRunResponse",
    "ProductionRunDetailResponse",
    "ProductionRunListResponse",
    # Production Run Item schemas
    "ProductionRunItemBase",
    "ProductionRunItemCreate",
    "ProductionRunItemUpdate",
    "ProductionRunItemResponse",
    # Production Run Material schemas
    "ProductionRunMaterialBase",
    "ProductionRunMaterialCreate",
    "ProductionRunMaterialUpdate",
    "ProductionRunMaterialResponse",
    # Production Run Plate schemas (multi-plate runs)
    "ProductionRunPlateBase",
    "ProductionRunPlateCreate",
    "ProductionRunPlateUpdate",
    "ProductionRunPlateResponse",
    "ProductionRunPlateListResponse",
    "ProductionRunPlateSummary",
    "MarkPlateCompleteRequest",
    # Summary schemas
    "ModelSummary",
    "ProductSummary",
    # SpoolmanDB schemas
    "SpoolmanDBManufacturerResponse",
    "SpoolmanDBManufacturerWithCount",
    "SpoolmanDBManufacturerListResponse",
    "SpoolmanDBFilamentResponse",
    "SpoolmanDBFilamentWithManufacturer",
    "SpoolmanDBFilamentListResponse",
    "SpoolmanDBSyncResponse",
    "SpoolmanDBStatsResponse",
    # Payment schemas
    "CartItem",
    "CustomerDetails",
    "PaymentError",
    "PaymentRequest",
    "PaymentResponse",
    "ShippingAddress",
    # Designer schemas
    "DesignerCreate",
    "DesignerUpdate",
    "DesignerResponse",
    "DesignerListResponse",
    "DesignerSimple",
    "DesignerPublic",
    # Shop schemas (public storefront API)
    "ShopCategoryListResponse",
    "ShopCategoryResponse",
    "ShopCategorySummary",
    "ShopDragonListResponse",
    "ShopProductDetail",
    "ShopProductFilters",
    "ShopProductImageResponse",
    "ShopProductListResponse",
    "ShopProductSummary",
    # Tenant Settings schemas
    "SquareSettingsUpdate",
    "SquareSettingsResponse",
    "SquareConnectionTest",
    "TenantResponse",
    "TenantUpdate",
    "TenantMemberResponse",
    "TenantMemberInvite",
    "TenantMemberRoleUpdate",
    "TenantMemberListResponse",
    "UserRole",
]
