# Woodpecker CI Pipeline for Nozzly - Hybrid Optimized
# Uses Kaniko for Docker builds (no DinD required, works on k8s)
#
# Hybrid Optimization Strategy:
# - Single backend test step with 4 parallel workers (avoids 3x poetry install overhead)
# - Docker builds start immediately after dep scan (don't wait for tests)
# - Security scans gate deployment (require both builds AND tests)
#
# Architecture:
# scan-deps-backend ──┬──> backend (lint + tests, 4 workers) ─────────┐
#                     └──> build-backend ─────────────────────────────┼──> scan-backend ──┐
#                                                                     │                   │
# scan-deps-frontend ─┬──> frontend ──────────────────────────────────┤                   ├──> deploy
#                     └──> build-frontend ────────────────────────────┴──> scan-frontend ─┘
#
# Expected time: ~25-28 min
#
when:
  - event: push
    branch: main
    path:
      exclude:
        - 'infrastructure/k8s/**'

variables:
  - &proxy_cache registry.techize.co.uk/dockerhub-cache
  - &python_image registry.techize.co.uk/dockerhub-cache/python:3.12-slim
  - &node_image registry.techize.co.uk/dockerhub-cache/node:20-slim
  - &registry registry.techize.co.uk

services:
  postgres:
    image: registry.techize.co.uk/dockerhub-cache/postgres:15
    ports:
      - 5432
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test_nozzly

steps:
  # ============================================
  # Dependency Vulnerability Scanning (parallel)
  # ============================================
  scan-deps-backend:
    image: aquasec/trivy:latest
    commands:
      - trivy fs --severity HIGH,CRITICAL --exit-code 1 --scanners vuln backend/
      - echo "Backend dependencies scan passed"

  scan-deps-frontend:
    image: aquasec/trivy:latest
    commands:
      - trivy fs --severity HIGH,CRITICAL --exit-code 1 --scanners vuln frontend/
      - echo "Frontend dependencies scan passed"

  # ============================================
  # Backend: Lint + Test (single step, 4 workers)
  # ============================================
  backend:
    image: *python_image
    depends_on:
      - scan-deps-backend
    environment:
      DATABASE_URL: postgresql+psycopg://test:test@postgres:5432/test_nozzly
      SECRET_KEY: test-secret-key-for-ci
      PGPASSWORD: test
    commands:
      - cd backend
      - pip install --quiet poetry
      - echo "=== Installing dependencies ==="
      - poetry install --no-interaction --quiet
      - echo "=== Creating worker databases for parallel tests ==="
      - apt-get update -qq && apt-get install -y -qq postgresql-client > /dev/null
      - for i in 0 1 2 3; do psql -h postgres -U test -d test_nozzly -c "CREATE DATABASE test_nozzly_gw$i" 2>/dev/null || true; done
      - echo "=== Running linters ==="
      - poetry run ruff check .
      - poetry run ruff format --check .
      - echo "=== Running tests (4 parallel workers) ==="
      - poetry run pytest tests/ -n 4 --dist worksteal --tb=short -q

  # ============================================
  # Frontend: Lint + Test
  # ============================================
  frontend:
    image: *node_image
    depends_on:
      - scan-deps-frontend
    commands:
      - cd frontend
      - echo "=== Installing dependencies ==="
      - npm ci --silent
      - echo "=== Running linters ==="
      - npm run lint
      - npm run typecheck
      - echo "=== Running tests ==="
      - npm test -- --run

  # ============================================
  # Build Docker Images (start early, parallel with tests)
  # Don't wait for tests - security scans gate deployment
  # ============================================
  build-backend:
    image: plugins/kaniko
    depends_on:
      - scan-deps-backend
    settings:
      repo: registry.techize.co.uk/nozzly/nozzly-backend
      dockerfile: backend/Dockerfile
      context: backend
      tags:
        - ${CI_COMMIT_SHA}
        - latest
      registry: registry.techize.co.uk
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  build-frontend:
    image: plugins/kaniko
    depends_on:
      - scan-deps-frontend
    settings:
      repo: registry.techize.co.uk/nozzly/nozzly-frontend
      dockerfile: frontend/Dockerfile
      context: frontend
      tags:
        - ${CI_COMMIT_SHA}
        - latest
      build_args:
        - VITE_API_URL=https://api.nozzly.app
      registry: registry.techize.co.uk
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password

  # ============================================
  # Security Scanning (gates deployment)
  # Requires both builds AND tests to pass
  # ============================================
  scan-backend:
    image: aquasec/trivy:latest
    depends_on:
      - build-backend
      - backend
    environment:
      TRIVY_USERNAME:
        from_secret: docker_username
      TRIVY_PASSWORD:
        from_secret: docker_password
    commands:
      - trivy image --severity HIGH,CRITICAL --exit-code 1 --ignore-unfixed registry.techize.co.uk/nozzly/nozzly-backend:${CI_COMMIT_SHA}
      - trivy image --format spdx-json --output /tmp/sbom-backend.json registry.techize.co.uk/nozzly/nozzly-backend:${CI_COMMIT_SHA}
      - echo "Backend security scan passed"

  scan-frontend:
    image: aquasec/trivy:latest
    depends_on:
      - build-frontend
      - frontend
    environment:
      TRIVY_USERNAME:
        from_secret: docker_username
      TRIVY_PASSWORD:
        from_secret: docker_password
    commands:
      - trivy image --severity HIGH,CRITICAL --exit-code 1 --ignore-unfixed registry.techize.co.uk/nozzly/nozzly-frontend:${CI_COMMIT_SHA}
      - trivy image --format spdx-json --output /tmp/sbom-frontend.json registry.techize.co.uk/nozzly/nozzly-frontend:${CI_COMMIT_SHA}
      - echo "Frontend security scan passed"

  # ============================================
  # Deploy to Staging
  # ============================================
  deploy-staging:
    image: registry.techize.co.uk/dockerhub-cache/alpine/git:latest
    depends_on:
      - scan-backend
      - scan-frontend
    environment:
      GIT_AUTHOR_NAME: woodpecker-ci[bot]
      GIT_AUTHOR_EMAIL: woodpecker-ci[bot]@nozzly.app
      GIT_COMMITTER_NAME: woodpecker-ci[bot]
      GIT_COMMITTER_EMAIL: woodpecker-ci[bot]@nozzly.app
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache sed curl
      - cd /woodpecker/src/github.com/techize/nozzly.app
      - 'echo "=== Deploying to STAGING ==="'
      - 'echo "Updating staging manifests with $CI_COMMIT_SHA..."'
      - 'sed -i "s|image: registry.techize.co.uk/nozzly/nozzly-backend:.*|image: registry.techize.co.uk/nozzly/nozzly-backend:$CI_COMMIT_SHA|g" infrastructure/k8s/staging/deployment.yaml'
      - git config --global --add safe.directory /woodpecker/src/github.com/techize/nozzly.app
      - 'git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/techize/nozzly.app.git'
      - git add infrastructure/k8s/staging/deployment.yaml
      - |
        for i in 1 2 3; do
          git pull --rebase origin main || true
          git diff --staged --quiet && echo "No staging changes to commit" && exit 0
          if git commit -m "cd(staging): update backend image to $CI_COMMIT_SHA" && git push origin main; then
            echo "Successfully pushed staging manifest update"
            exit 0
          fi
          echo "Attempt $i failed, retrying in 5s..."
          git reset HEAD~1 2>/dev/null || true
          sleep 5
        done
        echo "Failed after 3 attempts"
        exit 1

  # ============================================
  # Staging Health Check
  # ============================================
  health-check-staging:
    image: registry.techize.co.uk/dockerhub-cache/alpine:latest
    depends_on:
      - deploy-staging
    commands:
      - apk add --no-cache curl
      - echo "Waiting 30s for staging deployment to roll out..."
      - sleep 30
      - echo "Checking staging health..."
      - |
        for i in $(seq 1 10); do
          if curl -sf https://staging.nozzly.app/health | grep -q '"status":"healthy"'; then
            echo "Staging health check passed!"
            exit 0
          fi
          echo "Health check attempt $i failed, waiting 10s..."
          sleep 10
        done
        echo "Staging health check failed after 10 attempts"
        exit 1

  # ============================================
  # Deploy to Production
  # ============================================
  deploy-production:
    image: registry.techize.co.uk/dockerhub-cache/alpine/git:latest
    depends_on:
      - health-check-staging
    environment:
      GIT_AUTHOR_NAME: woodpecker-ci[bot]
      GIT_AUTHOR_EMAIL: woodpecker-ci[bot]@nozzly.app
      GIT_COMMITTER_NAME: woodpecker-ci[bot]
      GIT_COMMITTER_EMAIL: woodpecker-ci[bot]@nozzly.app
      GITHUB_TOKEN:
        from_secret: github_token
    commands:
      - apk add --no-cache sed
      - cd /woodpecker/src/github.com/techize/nozzly.app
      - 'echo "=== Deploying to PRODUCTION ==="'
      - 'echo "Updating production manifests with $CI_COMMIT_SHA..."'
      - 'sed -i "s|image: registry.techize.co.uk/nozzly/nozzly-backend:.*|image: registry.techize.co.uk/nozzly/nozzly-backend:$CI_COMMIT_SHA|g" infrastructure/k8s/backend/deployment.yaml'
      - 'sed -i "s|image: registry.techize.co.uk/nozzly/nozzly-frontend:.*|image: registry.techize.co.uk/nozzly/nozzly-frontend:$CI_COMMIT_SHA|g" infrastructure/k8s/frontend/deployment.yaml'
      - git config --global --add safe.directory /woodpecker/src/github.com/techize/nozzly.app
      - 'git remote set-url origin https://x-access-token:$GITHUB_TOKEN@github.com/techize/nozzly.app.git'
      - git add infrastructure/k8s/backend/deployment.yaml infrastructure/k8s/frontend/deployment.yaml
      - |
        for i in 1 2 3; do
          git pull --rebase origin main || true
          git diff --staged --quiet && echo "No production changes to commit" && exit 0
          if git commit -m "cd(prod): update image tags to $CI_COMMIT_SHA" && git push origin main; then
            echo "Successfully pushed production manifest update"
            exit 0
          fi
          echo "Attempt $i failed, retrying in 5s..."
          git reset HEAD~1 2>/dev/null || true
          sleep 5
        done
        echo "Failed after 3 attempts"
        exit 1
